name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: $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
          GIST_ID: e2f139d9027a3bf16abb2bf3eced2605
          TIMEZONE: Asia/Taipei
